@DotNet8WebApi.GenericRepositoryPatternExample.Api_HostAddress = http://localhost:5269

GET {{DotNet8WebApi.GenericRepositoryPatternExample.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
